server:
  port: ${PORT:8080}
  shutdown: graceful
springdoc:
  swagger-ui:
    path: /
spring:
  main:
    banner-mode: off
  application:
    name: community-service
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devaneio
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:migrations/changelog.yml
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
