spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/devaneio
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
jwt:
  signing-key: MySigningKey
  signature-algorithm: hs256
