server:
  port: ${PORT:8080}
  shutdown: graceful
springdoc:
  swagger-ui:
    path: /
spring:
  main:
    banner-mode: off
  application:
    name: community-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:migrations/changelog.yml
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
jwt:
  signing-key: ${JWT_SIGNING_KEY}
  signature-algorithm: ${JWT_SIGNATURE_ALGORITHM}
  duration-in-millis: 3600000
